export default {
  login: "Razieh-Abedi",
  id: 90816493,
  node_id: "MDQ6VXNlcjkwODE2NDkz",
  avatar_url: "https://avatars.githubusercontent.com/u/90816493?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Razieh-Abedi",
  html_url: "https://github.com/Razieh-Abedi",
  followers_url: "https://api.github.com/users/Razieh-Abedi/followers",
  following_url:
    "https://api.github.com/users/Razieh-Abedi/following{/other_user}",
  gists_url: "https://api.github.com/users/Razieh-Abedi/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/Razieh-Abedi/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Razieh-Abedi/subscriptions",
  organizations_url: "https://api.github.com/users/Razieh-Abedi/orgs",
  repos_url: "https://api.github.com/users/Razieh-Abedi/repos",
  events_url: "https://api.github.com/users/Razieh-Abedi/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/Razieh-Abedi/received_events",
  type: "User",
  site_admin: false,
  name: "Razieh Abedi",
  company: null,
  blog: "http://linkedin.com/in/razieh-abedi-45674b226",
  location: null,
  email: null,
  hireable: null,
  bio: "Proficient in React.js (hooks),  JavaScript, HTML5, and CSS3. Competent in responsive web design, GIT, and BootStrap5. Skilled in WordPress and Photoshop",
  twitter_username: null,
  public_repos: 30,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2021-09-16T03:53:47Z",
  updated_at: "2022-11-25T08:58:59Z",
};
